export enum EmpresaTipo {
  RECURSOS_NATURALEZA_AGRICULTURA = 'Recursos de la naturaleza - Agricultura',
  RECURSOS_NATURALEZA_GANADERIA = 'Recursos de la naturaleza - Ganadería',
  RECURSOS_NATURALEZA_PESCA_ACUICULTURA = 'Recursos de la naturaleza - Pesca y Acuicultura',
  RECURSOS_NATURALEZA_SILVICULTURA = 'Recursos de la naturaleza - Silvicultura',
  RECURSOS_NATURALEZA_MINERIA = 'Recursos de la naturaleza - Minería',

  INDUSTRIA_ALIMENTARIA_BEBIDAS = 'Industria - Alimentaria y Bebidas',
  INDUSTRIA_TEXTIL_CONFECCION = 'Industria - Textil y Confección',
  INDUSTRIA_AUTOMOTRIZ = 'Industria - Automotriz',
  INDUSTRIA_QUIMICA_FARMACEUTICA = 'Industria - Química y Farmacéutica',
  INDUSTRIA_ELECTRONICA_INFORMATICA = 'Industria - Electrónica e Informática',
  INDUSTRIA_METALURGICA_SIDERURGICA = 'Industria - Metalúrgica y Siderúrgica',
  INDUSTRIA_CONSTRUCCION = 'Industria - Construcción',
  INDUSTRIA_ENERGIA_AGUA = 'Industria - Energía y Agua',

  SERVICIOS_COMERCIO_MAYORISTAS = 'Servicios - Comercio al por mayor (Mayoristas)',
  SERVICIOS_COMERCIO_MINORISTAS = 'Servicios - Comercio al por menor (Minoristas/Retail)',
  SERVICIOS_TRANSPORTE_LOGISTICA = 'Servicios - Transporte y Logística',
  SERVICIOS_TURISMO_HOSTELERIA = 'Servicios - Turismo y Hostelería',
  SERVICIOS_TELECOMUNICACIONES = 'Servicios - Telecomunicaciones',
  SERVICIOS_BANCA_FINANZAS = 'Servicios - Banca y Finanzas',
  SERVICIOS_SEGUROS = 'Servicios - Seguros',
  SERVICIOS_SALUD_SANIDAD = 'Servicios - Salud y Sanidad',
  SERVICIOS_EDUCACION_FORMACION = 'Servicios - Educación y Formación',
  SERVICIOS_PROFESIONALES = 'Servicios - Servicios Profesionales (Consultoría, Legal)',
  SERVICIOS_OCIO_ENTRETENIMIENTO = 'Servicios - Ocio y Entretenimiento',

  INDUSTRIA_CONOCIMIENTO_ID = 'Industria del conocimiento - Investigación y Desarrollo (I+D)',
  INDUSTRIA_CONOCIMIENTO_TI = 'Industria del conocimiento - Tecnologías de la Información (Software, Ciberseguridad)',
  INDUSTRIA_CONOCIMIENTO_IA_BIG_DATA = 'Industria del conocimiento - Inteligencia Artificial y Big Data',
  INDUSTRIA_CONOCIMIENTO_CONSULTORIA = 'Industria del conocimiento - Consultoría Estratégica Avanzada',
  INDUSTRIA_CONOCIMIENTO_MEDIOS = 'Industria del conocimiento - Medios y Creación de Contenido Intelectual',

  SERVICIOS_PUBLICOS_ADMINISTRACION = 'Servicios públicos y sociales - Administración Pública y Gobierno',
  SERVICIOS_PUBLICOS_ORGANISMOS_INTERNACIONALES = 'Servicios públicos y sociales - Organismos Internacionales',
  SERVICIOS_PUBLICOS_ONG = 'Servicios públicos y sociales - Organizaciones No Gubernamentales (ONG)',
  SERVICIOS_PUBLICOS_SANITARIOS = 'Servicios públicos y sociales - Servicios Sanitarios Públicos',
  SERVICIOS_PUBLICOS_EDUCATIVOS = 'Servicios públicos y sociales - Servicios Educativos Públicos',
}
